function model = buildShowMotionModelHumanoid(params, model, task, Qs, pfi)

nb = 0;
% Base x translation (no mass)
nb = nb + 1;
model.appearance.body{nb} = {};
% Base z translation (no mass)
nb = nb + 1;
model.appearance.body{nb} = {};
% Base pitch (body mass)
nb = nb + 1;
model.appearance.body{nb} = ...
    { 'box', [-0.5*params.body_length -0.5*params.body_width 0.*params.body_height;...
    0.5*params.body_length 0.5*params.body_width 1.0*params.body_height]};

% Loop through arms (only one in 2D model)
for arm = 1:model.NARMS
    % Shoulder
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.upper_arm_rad 0; 0 -0.5*params.body_width-0.5*params.upper_arm_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.upper_arm_rad 0; 0 0.5*params.body_width-0.5*params.upper_arm_rad 0];
    cyl3 = [0 -0.5*params.body_width 0; 0 -0.5*params.body_width -params.l_upper_arm];
    cyl4 = [0 0.5*params.body_width 0; 0 0.5*params.body_width -params.l_upper_arm];
    model.appearance.body{nb} = ...
        {'cyl', cyl1, params.upper_arm_rad,...
        'cyl', cyl2, params.upper_arm_rad,...
        'cyl', cyl3, params.upper_arm_rad,...
        'cyl', cyl4, params.upper_arm_rad};
    % Elbow
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.forearm_rad 0; 0 -0.5*params.body_width-0.5*params.forearm_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.forearm_rad 0; 0 0.5*params.body_width-0.5*params.forearm_rad 0];
    cyl3 = [0 -0.5*params.body_width 0; 0 -0.5*params.body_width -params.l_forearm];
    cyl4 = [0 0.5*params.body_width 0; 0 0.5*params.body_width -params.l_forearm];
    
    if (strcmp(task,'dunk'))
        model.appearance.body{nb} = ...
            {'cyl', cyl1, params.forearm_rad,...
            'cyl', cyl2, params.forearm_rad,...
            'cyl', cyl3, params.forearm_rad,...
            'cyl', cyl4, params.forearm_rad,...
            'sphere', [0 0 -params.l_forearm], 0.5*params.body_width};
    else
        model.appearance.body{nb} = ...
            {'cyl', cyl1, params.forearm_rad,...
            'cyl', cyl2, params.forearm_rad,...
            'cyl', cyl3, params.forearm_rad,...
            'cyl', cyl4, params.forearm_rad};
    end
    
end

% Loop through legs (only one in 2D model)
for leg = 1:model.NLEGS
    % Hip
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.thigh_rad 0; 0 -0.5*params.body_width-0.5*params.thigh_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.thigh_rad 0; 0 0.5*params.body_width-0.5*params.thigh_rad 0];
    cyl3 = [0 -0.5*params.body_width 0; 0 -0.5*params.body_width -params.l_thigh];
    cyl4 = [0 0.5*params.body_width 0; 0 0.5*params.body_width -params.l_thigh];
    model.appearance.body{nb} = ...
        {'cyl', cyl1, params.thigh_rad,...
        'cyl', cyl2, params.thigh_rad,...
        'cyl', cyl3, params.thigh_rad,...
        'cyl', cyl4, params.thigh_rad};
    % Knee
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.shank_rad 0; 0 -0.5*params.body_width-0.5*params.shank_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.shank_rad 0; 0 0.5*params.body_width-0.5*params.shank_rad 0];
    cyl3 = [0 -0.5*params.body_width 0; 0 -0.5*params.body_width -params.l_shank];
    cyl4 = [0 0.5*params.body_width 0; 0 0.5*params.body_width -params.l_shank];
    model.appearance.body{nb} = ...
        {'cyl', cyl1, params.shank_rad,...
        'cyl', cyl2, params.shank_rad,...
        'cyl', cyl3, params.shank_rad,...
        'cyl', cyl4, params.shank_rad};
    % Ankle
    nb = nb + 1;
    lt = norm([params.foot_height params.l_toe]); tt = atan(params.foot_height/params.l_toe);
    lh = norm([params.foot_height params.l_heel]);th = atan(params.foot_height/params.l_heel);
    model.appearance.body{nb} = ...
        {'cyl', [0 0.5*params.body_width 0;-lh*cos(th) 0.5*params.body_width -lh*sin(th)],params.heel_rad,...
        'cyl', [0 0.5*params.body_width 0;lt*cos(tt) 0.5*params.body_width -lt*sin(tt)],params.toe_rad,...
        'cyl', [0 -0.5*params.body_width 0;-lh*cos(th) -0.5*params.body_width -lh*sin(th)],params.heel_rad,...
        'cyl', [0 -0.5*params.body_width 0;lt*cos(tt) -0.5*params.body_width -lt*sin(tt)],params.toe_rad}; 
end

% Base
switch task
    case 'dunk'
        % Animate hoop
        hoop_height = 0.4;%[0;0;1]'*ph_sym1(Qs(:,end)) - 0.06;
        hoop_radius = 0.1;
        hoop_x_position = [1;0;0]'*ph_sym1(Qs(:,end)) + 0.5*hoop_radius;
        net_len = 0.05;
        bb_thick = 0.02;
        bb_width_mult = 1.65;
        model.appearance.base = ...
            { 'box', [-1.5 -1.5 pfi{1}(2);...
            1.5 1.5 pfi{1}(2)-0.01],...
            'cyl',[hoop_x_position 0 hoop_height;...
            hoop_x_position 0 hoop_height-net_len],hoop_radius,...
            'box', [hoop_x_position+hoop_radius -bb_width_mult.*hoop_radius hoop_height;...
            hoop_x_position+hoop_radius+bb_thick bb_width_mult.*hoop_radius hoop_height+0.15]};   
    otherwise
        model.appearance.base = ...
            { 'box', [-1.5 -1.5 pfi{1}(2);...
            1.5 1.5 pfi{1}(2)-0.01]};

end