function model = buildShowMotionModelMC(params, model, pfi)

nb = 0;
% Base x translation (no mass)
nb = nb + 1;
model.appearance.body{nb} = {};
% Base z translation (no mass)
nb = nb + 1;
model.appearance.body{nb} = {};
% Base pitch (body mass)
nb = nb + 1;
model.appearance.body{nb} = ...
    { 'box', [-0.5*params.body_length -0.5*params.body_width -0.5*params.body_height;...
    0.5*params.body_length 0.5*params.body_width 0.5*params.body_height]};

% Loop through legs (only one in 2D model)
ss = [1 -1];
for leg = 1:model.NLEGS
    % Hip
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.leg_rad 0;...
        0 -0.5*params.body_width-0.5*params.leg_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.leg_rad 0;...
        0 0.5*params.body_width-0.5*params.leg_rad 0];
    cyl3 = [0 -0.5*params.body_width 0;...
        0 -0.5*params.body_width -params.l1];
    cyl4 = [0 0.5*params.body_width 0;...
        0 0.5*params.body_width -params.l1];
    model.appearance.body{nb} = ...
        {'cyl', cyl1, params.leg_rad,...
        'cyl', cyl2, params.leg_rad,...
        'cyl', cyl3, params.leg_rad,...
        'cyl', cyl4, params.leg_rad};
    
    % Knee
    nb = nb + 1;
    cyl1 = [0 -0.5*params.body_width+0.5*params.leg_rad 0;...
        0 -0.5*params.body_width-0.5*params.leg_rad 0];
    cyl2 = [0 0.5*params.body_width+0.5*params.leg_rad 0;...
        0 0.5*params.body_width-0.5*params.leg_rad 0];
    cyl3 = [0 -0.5*params.body_width 0;...
        0 -0.5*params.body_width -params.l2];
    cyl4 = [0 0.5*params.body_width 0;...
        0 0.5*params.body_width -params.l2];
    model.appearance.body{nb} = ...
        {'cyl', cyl1, params.leg_rad,...
        'cyl', cyl2, params.leg_rad,...
        'cyl', cyl3, params.leg_rad,...
        'cyl', cyl4, params.leg_rad};
end

% Base
model.appearance.base = ...
    { 'box', [-1.5 -1.5 pfi{1}(2);...
    10.5 1.5 pfi{1}(2)-0.01]};
